### ISSUE TITLE
Integrate CI-Server

### ISSUE THREAD

**Issue by jonashackt** [codecentric/reedelk-runtime#3]
Hey there, great to have to project at the codecentric orga 👏  But it seems that there isn't any CI configured, that regularly builds the code and runs the tests... So what about using GitHub Actions?

**Comment by jonashackt** [comment]
Ok, I get local build failures 😲 `mvn clean install` leads to:

```
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /Users/jonashecht/dev/reedelk-runtime/runtime-api/target/surefire-reports/2020-12-23T13-41-10_988-jvmRun1.dumpstream
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for reedelk-runtime 1.0.6:
[INFO]
[INFO] reedelk-runtime .................................... SUCCESS [  0.392 s]
[INFO] runtime-api ........................................ FAILURE [  4.430 s]
[INFO] module-descriptor .................................. SKIPPED
[INFO] module-maven-plugin ................................ SKIPPED
[INFO] runtime-commons .................................... SKIPPED
[INFO] runtime-platform ................................... SKIPPED
[INFO] runtime-admin-console .............................. SKIPPED
[INFO] runtime-launcher ................................... SKIPPED
[INFO] module-parent ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.433 s
[INFO] Finished at: 2020-12-23T13:41:12+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project runtime-api: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/jonashecht/dev/reedelk-runtime/runtime-api/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/jonashecht/dev/reedelk-runtime/runtime-api && /Users/jonashecht/.sdkman/candidates/java/15.0.1.hs-adpt/bin/java -javaagent:/Users/jonashecht/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/Users/jonashecht/dev/reedelk-runtime/runtime-api/target/jacoco.exec -jar /Users/jonashecht/dev/reedelk-runtime/runtime-api/target/surefire/surefirebooter16965030777789669412.jar /Users/jonashecht/dev/reedelk-runtime/runtime-api/target/surefire 2020-12-23T13-41-10_988-jvmRun1 surefire16773857528944312151tmp surefire_01575155092898850955tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/jonashecht/dev/reedelk-runtime/runtime-api && /Users/jonashecht/.sdkman/candidates/java/15.0.1.hs-adpt/bin/java -javaagent:/Users/jonashecht/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/Users/jonashecht/dev/reedelk-runtime/runtime-api/target/jacoco.exec -jar /Users/jonashecht/dev/reedelk-runtime/runtime-api/target/surefire/surefirebooter16965030777789669412.jar /Users/jonashecht/dev/reedelk-runtime/runtime-api/target/surefire 2020-12-23T13-41-10_988-jvmRun1 surefire16773857528944312151tmp surefire_01575155092898850955tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:690)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:248)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1217)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1063)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:889)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :runtime-api
```

**Comment by jonashackt** [comment]
Ah, wie JDK8 it works perfectly fine locally 🙉

**Comment by danielkocot** [comment]
The build and release management works good for the first iteration.
